services:
  ${PROJECT_LOWER}-${SERVICE_NAME}-${STACK_NAME}:
    image: ghcr.io/${REPO_LOWER}-${SERVICE_NAME}:image-placeholder
    networks:
      - traefik-public
      - default
    environment:
      NODE_ENV: "production"
      PORT: "${CLIENT_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${CLIENT_PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${PROJECT_LOWER}-${SERVICE_NAME}-${STACK_NAME}.rule=(Host(`${DOMAIN_NAME}`) || Host(`www.${DOMAIN_NAME}`)) && PathPrefix(`/`)"
        - "traefik.http.routers.${PROJECT_LOWER}-${SERVICE_NAME}-${STACK_NAME}.entrypoints=websecure"
        - "traefik.http.routers.${PROJECT_LOWER}-${SERVICE_NAME}-${STACK_NAME}.tls.certresolver=letsencrypt"
        - "traefik.http.routers.${PROJECT_LOWER}-${SERVICE_NAME}-${STACK_NAME}.service=${PROJECT_LOWER}-${SERVICE_NAME}-${STACK_NAME}"
        - "traefik.http.middlewares.hsts-header.headers.stsSeconds=31536000"
        - "traefik.http.middlewares.hsts-header.headers.stsIncludeSubdomains=true"
        - "traefik.http.middlewares.hsts-header.headers.stsPreload=true"
        - "traefik.http.routers.${PROJECT_LOWER}-${SERVICE_NAME}-${STACK_NAME}.middlewares=hsts-header@swarm"
        - "traefik.http.services.${PROJECT_LOWER}-${SERVICE_NAME}-${STACK_NAME}.loadbalancer.server.port=${CLIENT_PORT}"

networks:
  traefik-public:
    external: true
  default:
    driver: overlay